**Bag of words**

**TF-IDF**

In [1]:
import numpy as np
import pandas as pd
import re as re

In [3]:
path = 'C:/Users/Chi Khang/Documents/imdb-review-classification/data'

train_set = pd.read_csv(path + "/train.csv")
valid_set = pd.read_csv(path + "/val.csv")
test_set = pd.read_csv(path + "/test.csv")

In [12]:
data_raw = pd.concat([train_set,valid_set])
data_raw = pd.concat([data_raw,test_set])
data_raw

review sentiment
0     In this approximately 34-second Thomas Edison-...  positive
1     Basically there's a family where a little boy ...  negative
2     A sentimental school drama set in Denmark, 196...  negative
3     This must be one of the worst movies I have ev...  negative
4     Very good film. Very good documentary.<br /><b...  positive
...                                                 ...       ...
1995  Oh boy! Oh boy! On the cover of worn out VHS h...  negative
1996  "The Man In The Attic" is a movie set in the 1...  negative
1997  I rented the film (I don't think it got a thea...  positive
1998  Well, i can and will be very short. This is a ...  negative
1999  I'm far from a Sylvester Stallone fan and I gu...  positive

[50000 rows x 2 columns]

In [13]:
data_raw['sentiment'] = data_raw['sentiment'].apply(lambda x: 1 if x=='negative' else 0)

In [14]:
data_raw

review  sentiment
0     In this approximately 34-second Thomas Edison-...          0
1     Basically there's a family where a little boy ...          1
2     A sentimental school drama set in Denmark, 196...          1
3     This must be one of the worst movies I have ev...          1
4     Very good film. Very good documentary.<br /><b...          0
...                                                 ...        ...
1995  Oh boy! Oh boy! On the cover of worn out VHS h...          1
1996  "The Man In The Attic" is a movie set in the 1...          1
1997  I rented the film (I don't think it got a thea...          0
1998  Well, i can and will be very short. This is a ...          1
1999  I'm far from a Sylvester Stallone fan and I gu...          0

[50000 rows x 2 columns]

# **Data Preparation**

### **Data Cleaning**

**Step 1 : Remove HTML tags**

In [11]:
def remove_html_tag(text: str) -> str:
    text_copy  =str(text)
    HTML_TAG_PATTERN = re.compile('<.*?>')
    text_copy = re.sub(HTML_TAG_PATTERN," ",text_copy)
    return text_copy

In [12]:
data_raw["clean_review"] = np.vectorize(remove_html_tag)(data_raw["review"])
data_raw.head(10)

review  sentiment  \
0  My family and I normally do not watch local mo...          1   
1  Believe it or not, this was at one time the wo...          0   
2  After some internet surfing, I found the "Home...          0   
3  One of the most unheralded great works of anim...          1   
4  It was the Sixties, and anyone with long hair ...          0   
5  For my humanities quarter project for school, ...          1   
6  Arguebly Al Pacino's best role. He plays Tony ...          1   
7  Being a big fan of Stanley Kubrick's Clockwork...          1   
8  I reached the end of this and I was almost sho...          1   
9  There is no doubt that Halloween is by far one...          1   

                                        clean_review  
0  My family and I normally do not watch local mo...  
1  Believe it or not, this was at one time the wo...  
2  After some internet surfing, I found the "Home...  
3  One of the most unheralded great works of anim...  
4  It was the Sixties, and anyone with long hair ...  
5  For my humanities quarter project for school, ...  
6  Arguebly Al Pacino's best role. He plays Tony ...  
7  Being a big fan of Stanley Kubrick's Clockwork...  
8  I reached the end of this and I was almost sho...  
9  There is no doubt that Halloween is by far one...

In [13]:
data_raw["clean_review"][0]

'My family and I normally do not watch local movies for the simple reason that they are poorly made, they lack the depth, and just not worth our time.  The trailer of "Nasaan ka man" caught my attention, my daughter in law\'s and daughter\'s so we took time out to watch it this afternoon. The movie exceeded our expectations. The cinematography was very good, the story beautiful and the acting awesome. Jericho Rosales was really very good, so\'s Claudine Barretto. The fact that I despised Diether Ocampo proves he was effective at his role. I have never been this touched, moved and affected by a local movie before. Imagine a cynic like me dabbing my eyes at the end of the movie? Congratulations to Star Cinema!! Way to go, Jericho and Claudine!!'

**Step 2 : Remove Punctuation, Numbers, Emojis, Special Characters**

In [14]:
def remove_special_charater(text: str) -> str:
    text_copy = str(text)
    text_copy.replace("[^a-zA-Z#]", " ")
    return text_copy

In [15]:
data_raw['clean_review'] = data_raw['clean_review'].str.replace("[^a-zA-Z#]", " ")

data_raw.head(10)

C:\Users\Chi Khang\AppData\Local\Temp\ipykernel_11032\3680168625.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  data_raw['clean_review'] = data_raw['clean_review'].str.replace("[^a-zA-Z#]", " ")


review  sentiment  \
0  My family and I normally do not watch local mo...          1   
1  Believe it or not, this was at one time the wo...          0   
2  After some internet surfing, I found the "Home...          0   
3  One of the most unheralded great works of anim...          1   
4  It was the Sixties, and anyone with long hair ...          0   
5  For my humanities quarter project for school, ...          1   
6  Arguebly Al Pacino's best role. He plays Tony ...          1   
7  Being a big fan of Stanley Kubrick's Clockwork...          1   
8  I reached the end of this and I was almost sho...          1   
9  There is no doubt that Halloween is by far one...          1   

                                        clean_review  
0  My family and I normally do not watch local mo...  
1  Believe it or not  this was at one time the wo...  
2  After some internet surfing  I found the  Home...  
3  One of the most unheralded great works of anim...  
4  It was the Sixties  and anyone with long hair ...  
5  For my humanities quarter project for school  ...  
6  Arguebly Al Pacino s best role  He plays Tony ...  
7  Being a big fan of Stanley Kubrick s Clockwork...  
8  I reached the end of this and I was almost sho...  
9  There is no doubt that Halloween is by far one...

In [ ]:
data_raw["clean_review"][0]

'My family and I normally do not watch local movies for the simple reason that they are poorly made  they lack the depth  and just not worth our time   The trailer of  Nasaan ka man  caught my attention  my daughter in law s and daughter s so we took time out to watch it this afternoon  The movie exceeded our expectations  The cinematography was very good  the story beautiful and the acting awesome  Jericho Rosales was really very good  so s Claudine Barretto  The fact that I despised Diether Ocampo proves he was effective at his role  I have never been this touched  moved and affected by a local movie before  Imagine a cynic like me dabbing my eyes at the end of the movie  Congratulations to Star Cinema   Way to go  Jericho and Claudine  '

In [ ]:
data_raw["clean_review"][15]

'Rather like Paul Newman and Steve McQueen with their racing car movies this has all the appearance of a  jollies  project for Robert Redford  as he gets to ski up hill and down dale in the Alpine sunshine   The story is as light as powdered snow with Redford s small town boy David Chappellet  what kind of lead name is that   who with his eyes on the prize of Olympic glory  gets up the nose of  in no particular order  his coach  father and team mates  Women are a mere side show in his insular world as evidenced by a fairly distasteful pick up scene with an old girlfriend in his hometown and then his selfishly petulant pursuit of  heavens above  a free thinking  independent woman  played by Camilla Sparv  The ski ing sequences are fine with some good stunt work involving numerous bumps and scrapes on the piste but their effectiveness is dimmed by our subsequent familiarity with top TV coverage of skiing events down to the present day  Plus I m not convinced that the Winter Olympics has 

**Step 3: Lowercasting**

In [ ]:
import string
def lower_casting(string):
    string = string.lower()
    return string

In [ ]:
data_raw["clean_review"] = np.vectorize(lower_casting)(data_raw["clean_review"])
data_raw["clean_review"][15]

'rather like paul newman and steve mcqueen with their racing car movies this has all the appearance of a  jollies  project for robert redford  as he gets to ski up hill and down dale in the alpine sunshine   the story is as light as powdered snow with redford s small town boy david chappellet  what kind of lead name is that   who with his eyes on the prize of olympic glory  gets up the nose of  in no particular order  his coach  father and team mates  women are a mere side show in his insular world as evidenced by a fairly distasteful pick up scene with an old girlfriend in his hometown and then his selfishly petulant pursuit of  heavens above  a free thinking  independent woman  played by camilla sparv  the ski ing sequences are fine with some good stunt work involving numerous bumps and scrapes on the piste but their effectiveness is dimmed by our subsequent familiarity with top tv coverage of skiing events down to the present day  plus i m not convinced that the winter olympics has 

In [ ]:
data_raw["clean_review"][00]

'my family and i normally do not watch local movies for the simple reason that they are poorly made  they lack the depth  and just not worth our time   the trailer of  nasaan ka man  caught my attention  my daughter in law s and daughter s so we took time out to watch it this afternoon  the movie exceeded our expectations  the cinematography was very good  the story beautiful and the acting awesome  jericho rosales was really very good  so s claudine barretto  the fact that i despised diether ocampo proves he was effective at his role  i have never been this touched  moved and affected by a local movie before  imagine a cynic like me dabbing my eyes at the end of the movie  congratulations to star cinema   way to go  jericho and claudine  '

**Step 4: Remove Stop Words**

In [ ]:
data_raw["clean_review"] = data_raw["clean_review"].apply(lambda x: ' '.join([w for w in x.split() if len(w)>3]))

data_raw.head(10)

review  sentiment  \
0  My family and I normally do not watch local mo...          1   
1  Believe it or not, this was at one time the wo...          0   
2  After some internet surfing, I found the "Home...          0   
3  One of the most unheralded great works of anim...          1   
4  It was the Sixties, and anyone with long hair ...          0   
5  For my humanities quarter project for school, ...          1   
6  Arguebly Al Pacino's best role. He plays Tony ...          1   
7  Being a big fan of Stanley Kubrick's Clockwork...          1   
8  I reached the end of this and I was almost sho...          1   
9  There is no doubt that Halloween is by far one...          1   

                                        clean_review  
0  family normally watch local movies simple reas...  
1  believe this time worst movie ever seen since ...  
2  after some internet surfing found homefront se...  
3  most unheralded great works animation though m...  
4  sixties anyone with long hair distant attitude...  
5  humanities quarter project school chose human ...  
6  arguebly pacino best role plays tony montana s...  
7  being stanley kubrick clockwork orange there c...  
8  reached this almost shouting cannot here there...  
9  there doubt that halloween best films ever onl...

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.corpus import stopwords
stop = stopwords.words('english')
print(stop)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [ ]:
data_raw["clean_review"] = data_raw["clean_review"].apply(lambda x: ' '.join([w for w in x.split() if w not in stop]))

In [ ]:
data_raw.head(10)

review  sentiment  \
0  My family and I normally do not watch local mo...          1   
1  Believe it or not, this was at one time the wo...          0   
2  After some internet surfing, I found the "Home...          0   
3  One of the most unheralded great works of anim...          1   
4  It was the Sixties, and anyone with long hair ...          0   
5  For my humanities quarter project for school, ...          1   
6  Arguebly Al Pacino's best role. He plays Tony ...          1   
7  Being a big fan of Stanley Kubrick's Clockwork...          1   
8  I reached the end of this and I was almost sho...          1   
9  There is no doubt that Halloween is by far one...          1   

                                        clean_review  
0  family normally watch local movies simple reas...  
1  believe time worst movie ever seen since time ...  
2  internet surfing found homefront series ioffer...  
3  unheralded great works animation though makes ...  
4  sixties anyone long hair distant attitude coul...  
5  humanities quarter project school chose human ...  
6  arguebly pacino best role plays tony montana s...  
7  stanley kubrick clockwork orange course questi...  
8  reached almost shouting cannot many unanswered...  
9  doubt halloween best films ever genre also out...

In [ ]:
data_raw['clean_review'][15]

'rather like paul newman steve mcqueen racing movies appearance jollies project robert redford gets hill dale alpine sunshine story light powdered snow redford small town david chappellet kind lead name eyes prize olympic glory gets nose particular order coach father team mates women mere side show insular world evidenced fairly distasteful pick scene girlfriend hometown selfishly petulant pursuit heavens free thinking independent woman played camilla sparv sequences fine good stunt work involving numerous bumps scrapes piste effectiveness dimmed subsequent familiarity coverage skiing events present plus convinced winter olympics mass identification general public summer games redford eventually wins gold medal final reel really excited another actors redford best profile forward need much indeed gene hackman better equally meagre material sparv well chief female interest well treats redford doubtless treated every woman chauvinistic truth though lack dramatic tension throughout action

In [ ]:
data_raw['clean_review'][0]

'family normally watch local movies simple reason poorly made lack depth worth time trailer nasaan caught attention daughter daughter took time watch afternoon movie exceeded expectations cinematography good story beautiful acting awesome jericho rosales really good claudine barretto fact despised diether ocampo proves effective role never touched moved affected local movie imagine cynic like dabbing eyes movie congratulations star cinema jericho claudine'

**Step 5: Tokenization**

In [ ]:
tokenized_review = data_raw["clean_review"].apply(lambda x: x.split())
tokenized_review.head()

0    [family, normally, watch, local, movies, simpl...
1    [believe, time, worst, movie, ever, seen, sinc...
2    [internet, surfing, found, homefront, series, ...
3    [unheralded, great, works, animation, though, ...
4    [sixties, anyone, long, hair, distant, attitud...
Name: clean_review, dtype: object

In [ ]:
type(tokenized_review) #huh??

pandas.core.series.Series

**Step 6: Stemming**

In [ ]:
from nltk import PorterStemmer
ps = PorterStemmer()
tokenized_review = tokenized_review.apply(lambda x: [ps.stem(i) for i in x])

for i in range(len(tokenized_review)):
    tokenized_review[i] = ' '.join(tokenized_review[i])

data_raw["clean_review"] = tokenized_review
data_raw.head(5)

review  sentiment  \
0  My family and I normally do not watch local mo...          1   
1  Believe it or not, this was at one time the wo...          0   
2  After some internet surfing, I found the "Home...          0   
3  One of the most unheralded great works of anim...          1   
4  It was the Sixties, and anyone with long hair ...          0   

                                        clean_review  
0  famili normal watch local movi simpl reason po...  
1  believ time worst movi ever seen sinc time see...  
2  internet surf found homefront seri ioffer anyo...  
3  unherald great work anim though make sophist m...  
4  sixti anyon long hair distant attitud could mo...

In [ ]:
data_raw["clean_review"][0]

'famili normal watch local movi simpl reason poorli made lack depth worth time trailer nasaan caught attent daughter daughter took time watch afternoon movi exceed expect cinematographi good stori beauti act awesom jericho rosal realli good claudin barretto fact despis diether ocampo prove effect role never touch move affect local movi imagin cynic like dab eye movi congratul star cinema jericho claudin'

In [ ]:
data_raw["clean_review"][15]

'rather like paul newman steve mcqueen race movi appear jolli project robert redford get hill dale alpin sunshin stori light powder snow redford small town david chappellet kind lead name eye prize olymp glori get nose particular order coach father team mate women mere side show insular world evidenc fairli distast pick scene girlfriend hometown selfishli petul pursuit heaven free think independ woman play camilla sparv sequenc fine good stunt work involv numer bump scrape pist effect dim subsequ familiar coverag ski event present plu convinc winter olymp mass identif gener public summer game redford eventu win gold medal final reel realli excit anoth actor redford best profil forward need much inde gene hackman better equal meagr materi sparv well chief femal interest well treat redford doubtless treat everi woman chauvinist truth though lack dramat tension throughout action sequenc fulli compens care lead charact film actor probabl enjoy make viewer watch'

### **Feature Extraction**

**Bag of Words**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

bow_vectorizer = CountVectorizer(max_df=0.90, min_df=2, max_features=1000, stop_words = "english")

bow = bow_vectorizer.fit_transform(data_raw['clean_review'])

In [ ]:
df_bow = pd.DataFrame(bow.todense())
df_bow.shape

(50000, 1000)

In [ ]:
df_bow.head(10)

0    1    2    3    4    5    6    7    8    9    ...  990  991  992  993  \
0    0    0    0    0    0    0    1    0    0    0  ...    0    0    0    0   
1    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
2    0    1    0    0    0    0    2    0    1    0  ...    2    0    0    0   
3    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
4    1    3    0    0    0    0    0    0    0    1  ...    1    0    0    0   
5    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
6    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
7    0    1    0    0    0    0    0    0    0    0  ...    0    0    0    0   
8    0    0    0    0    0    0    0    0    2    0  ...    0    0    0    0   
9    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

   994  995  996  997  998  999  
0    0    0    0    0    0    0  
1    0    0    0    0    0    0  
2    0    3    0    0    0    0  
3    0    0    0    0    0    0  
4    0    1    0    0    0    0  
5    0    1    0    0    0    0  
6    0    0    0    1    0    0  
7    0    1    0    0    0    0  
8    0    0    0    0    0    1  
9    0    0    0    0    0    1  

[10 rows x 1000 columns]

**TF-IDF**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_df=0.90, min_df=2, max_features=1000, stop_words="english")

tfidf_matrix = tfidf.fit_transform(data_raw['clean_review'])

df_tfidf = pd.DataFrame(tfidf_matrix.todense())

df_tfidf


0         1         2         3    4    5         6    7    \
0      0.000000  0.000000  0.000000  0.000000  0.0  0.0  0.094116  0.0   
1      0.000000  0.000000  0.000000  0.000000  0.0  0.0  0.000000  0.0   
2      0.000000  0.047927  0.000000  0.000000  0.0  0.0  0.056984  0.0   
3      0.000000  0.000000  0.000000  0.000000  0.0  0.0  0.000000  0.0   
4      0.084656  0.211770  0.000000  0.000000  0.0  0.0  0.000000  0.0   
...         ...       ...       ...       ...  ...  ...       ...  ...   
49995  0.000000  0.000000  0.123319  0.000000  0.0  0.0  0.000000  0.0   
49996  0.124053  0.000000  0.000000  0.366157  0.0  0.0  0.000000  0.0   
49997  0.000000  0.000000  0.000000  0.000000  0.0  0.0  0.000000  0.0   
49998  0.000000  0.000000  0.000000  0.000000  0.0  0.0  0.000000  0.0   
49999  0.000000  0.000000  0.000000  0.000000  0.0  0.0  0.000000  0.0   

            8         9    ...       990  991       992  993  994       995  \
0      0.000000  0.000000  ...  0.000000  0.0  0.000000  0.0  0.0  0.000000   
1      0.000000  0.000000  ...  0.000000  0.0  0.000000  0.0  0.0  0.000000   
2      0.030650  0.000000  ...  0.090148  0.0  0.000000  0.0  0.0  0.093022   
3      0.000000  0.000000  ...  0.000000  0.0  0.000000  0.0  0.0  0.000000   
4      0.000000  0.069128  ...  0.066388  0.0  0.000000  0.0  0.0  0.045669   
...         ...       ...  ...       ...  ...       ...  ...  ...       ...   
49995  0.000000  0.000000  ...  0.000000  0.0  0.000000  0.0  0.0  0.000000   
49996  0.132305  0.000000  ...  0.097284  0.0  0.191204  0.0  0.0  0.000000   
49997  0.127258  0.000000  ...  0.093573  0.0  0.000000  0.0  0.0  0.064370   
49998  0.106742  0.000000  ...  0.000000  0.0  0.000000  0.0  0.0  0.000000   
49999  0.000000  0.000000  ...  0.000000  0.0  0.000000  0.0  0.0  0.000000   

       996  997  998  999  
0      0.0  0.0  0.0  0.0  
1      0.0  0.0  0.0  0.0  
2      0.0  0.0  0.0  0.0  
3      0.0  0.0  0.0  0.0  
4      0.0  0.0  0.0  0.0  
...    ...  ...  ...  ...  
49995  0.0  0.0  0.0  0.0  
49996  0.0  0.0  0.0  0.0  
49997  0.0  0.0  0.0  0.0  
49998  0.0  0.0  0.0  0.0  
49999  0.0  0.0  0.0  0.0  

[50000 rows x 1000 columns]

## **Machine Learning Models**

In [ ]:
from sklearn.metrics import f1_score

### **Split Training Set and test Set**

In [ ]:
train_bow = bow[:]
train_tfidf = tfidf_matrix[:]

In [ ]:
from sklearn.model_selection import train_test_split

# Bag of Word
x_train_bow, x_valid_bow, y_train_bow, y_valid_bow = train_test_split(train_bow,data_raw['sentiment'], test_size = 0.3, random_state=2)

# TF-IDF
x_train_tfidf, x_valid_tfidf, y_train_tfidf, y_valid_tfidf = train_test_split(train_tfidf,data_raw['sentiment'],test_size=0.3,random_state=17)

### **Logistic Regression**

**Bag of words**

In [ ]:
from sklearn.linear_model import LogisticRegression

LoRe = LogisticRegression(random_state=0, solver='lbfgs')

LoRe.fit(x_train_bow, y_train_bow)

# Predicting the probabilities

predict_bow = LoRe.predict_proba(x_valid_bow)

predict_bow

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


array([[0.85659371, 0.14340629],
       [0.99640414, 0.00359586],
       [0.95238468, 0.04761532],
       ...,
       [0.91920334, 0.08079666],
       [0.99256265, 0.00743735],
       [0.96118871, 0.03881129]])

In [ ]:
predict_int = predict_bow[:,1] >=0.5
predict_int

array([False, False, False, ..., False, False, False])

In [ ]:
predict_int = predict_int.astype(np.int)
predict_int

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
# calculating f1 score
log_bow = f1_score(y_valid_bow, predict_int)

print("F1 Score: ",log_bow)

F1 Score:  0.8594634178816324


**TF-IDF**

In [ ]:
LoRe.fit(x_train_tfidf,y_train_tfidf)

# Predicting the probabilities

prediction_tfidf = LoRe.predict_proba(x_valid_tfidf)

prediction_tfidf

array([[0.63923566, 0.36076434],
       [0.0610065 , 0.9389935 ],
       [0.62164023, 0.37835977],
       ...,
       [0.4262661 , 0.5737339 ],
       [0.05334726, 0.94665274],
       [0.32635101, 0.67364899]])

In [ ]:
prediction_int = prediction_tfidf[:,1] >=0.3

prediction_int = prediction_int.astype(np.int)

# Calculate F1 Score

log_tfidf = f1_score(y_valid_tfidf, prediction_int)

print("F1 score: ", log_tfidf)

F1 score:  0.8457224674859802


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  This is separate from the ipykernel package so we can avoid doing imports until


### **Decision Tree**

In [ ]:
from sklearn.tree import DecisionTreeClassifier

dct = DecisionTreeClassifier(criterion='entropy', random_state=1)

**Bag of words**

In [ ]:
dct.fit(x_train_bow, y_train_bow)

# Predict probability

dct_bow = dct.predict_proba(x_valid_bow)
dct_bow


array([[0., 1.],
       [1., 0.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [1., 0.]])

In [ ]:
# Calculate F1 Score

dct_bow = dct_bow[:,1] >= 0.3

dct_bow_int = dct_bow.astype(np.int)

dct_bow_score = f1_score(y_valid_bow, dct_bow_int)
print("F1 score: ", dct_bow_score)

F1 score:  0.7154744329620184


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """


**TF-IDF**

In [ ]:
dct.fit(x_train_tfidf, y_train_tfidf)

dct_tfidf = dct.predict_proba(x_valid_tfidf)
dct_tfidf

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [ ]:
dct_tfidf = dct_tfidf[:,1] >= 0.3
dct_tfidf_int = dct_tfidf.astype(np.int)

# Calculate F1 score

dct_tfidf_score = f1_score(y_valid_tfidf, dct_tfidf_int)

print("F1 Score: ", dct_tfidf_score)

F1 Score:  0.7163201176706558


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


# **Model Evaluation**